# Copyright 2016-2022 Swiss National Supercomputing Centre (CSCS/ETH Zurich)
# ReFrame Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause


#
# This file was automatically generated by ReFrame based on 'setup_files/settings.py'.  # noqa: E501
# Most of this file taken from Deva's settings.py file in reframe/setup_files/ on bitbucket
#

site_configuration = {
    'systems': [
        {
            'name': 'setonix',
            'descr': 'Setonix',
            'hostnames': ['setonix-01', 'setonix-02', 'setonix-03', 'setonix-04', 'setonix-05', 'setonix-06', 'setonix-07', 'setonix-08', 'setonix-09'],
            'modules_system': 'lmod',
            'partitions': [
                {
                    'name': 'login',
                    'descr': 'Setonix login node',
                    'scheduler': 'local',
                    'launcher': 'local',
                    'modules': [],
                    'access': [],
                    'max_jobs': 1,
                    'environs': [
                        'PrgEnv-gnu', # Default is gcc/12.1.0
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'work',
                    'descr': 'Setonix work (compute nodes) partition',
                    'scheduler': 'slurm', # Was slurm, job accounting seemingly changed after Jan 2023 maintenance
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=work'],
                    'max_jobs': 1024,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'askaprt',
                    'descr': 'Setonix askaprt (compute nodes) partition',
                    'scheduler': 'slurm', # Was slurm, job accounting seemingly changed after Jan 2023 maintenance
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=askaprt'],
                    'max_jobs': 8192,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'copy',
                    'descr': 'Setonix copy (data mover) nodes',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=copy'],
                    'max_jobs': 500,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'debug',
                    'descr': 'Setonix debug partition',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=debug'],
                    'max_jobs': 4,
                    'environs': ['PrgEnv-cray', 'PrgEnv-gnu'],
                },
                {
                    'name': 'highmem',
                    'descr': 'Setonix highmem queue',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=highmem'],
                    'max_jobs': 96,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ]
                },
                {
                    'name': 'gpu',
                    'descr': 'Setonix GPU queue',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [], # Might need to add add rocm
                    'access': ['--partition=gpu'],
                    'max_jobs': 1024,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                    'resources': [
                        {
                            'name': 'gpu',
                            'options': ['--gpus-per-node={num_gpus_per_node}']
                        }
                    ],
                },
                {
                    'name': 'gpu-dev',
                    'descr': 'Setonix GPU development queue',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=gpu-dev'],
                    'max_jobs': 4,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                    'resources': [
                        {
                            'name': 'gpu',
                            'options': ['--gpus-per-node={num_gpus_per_node}']
                        }
                    ],
                },
                {
                    'name': 'gpu-highmem',
                    'descr': 'Setonix GPU high memory queue',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=gpu-highmem'],
                    'max_jobs': 96,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                    'resources': [
                        {
                            'name': 'gpu',
                            'options': ['--gpus-per-node={num_gpus_per_node}']
                        }
                    ],
                },
            ]
        },
        {
            'name': 'joey',
            'descr': 'Joey test system',
            'hostnames': ['joey-01', 'joey-02'],
            'modules_system': 'lmod',
            'partitions': [
                {
                    'name': 'login',
                    'descr': 'Joey login node',
                    'scheduler': 'local',
                    'launcher': 'local',
                    'modules': [],
                    'access': [],
                    'max_jobs': 1,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'work',
                    'descr': 'Joey work queue',
                    'scheduler': 'slurm',
                    'sched_options': {
                        'use_nodes_option': True,
                    },
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=work'],
                    'max_jobs': 32,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'highmem',
                    'descr': 'Joey highmem queue',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=highmem'],
                    'max_jobs': 1,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                },
                {
                    'name': 'gpu',
                    'descr': 'Joey GPU queue',
                    'scheduler': 'slurm',
                    'sched_options': {
                        'use_nodes_option': True,
                    },
                    'launcher': 'srun',
                    'modules': [], # Might need to add add rocm
                    'access': ['--partition=gpu'],
                    'max_jobs': 8,
                    'environs': [
                        'PrgEnv-gnu',
                        'PrgEnv-cray',
                    ],
                    'resources': [
                        {
                            'name': 'gpu',
                            'options': ['--gpus-per-node={num_gpus_per_node}']
                        }
                    ],
                },
            ]
        },
    ],
    'environments': [
        {
            'name': 'PrgEnv-cray',
            'target_systems': ['setonix'],
            'modules': [
                'PrgEnv-cray/8.6.0',
                'cray-mpich/8.1.32',
                'cce/19.0.0',
            ]
        },
        {
            'name': 'PrgEnv-cray',
            'target_systems': ['joey'],
            'modules': [
                'PrgEnv-cray/8.7.0',
                'cray-mpich/9.1.0',
                'cce/21.0.0',
            ]
        },
        {
            'name': 'PrgEnv-gnu',
            'target_systems': ['setonix'],
            'modules': [
                'PrgEnv-gnu/8.6.0',
                'cray-mpich/8.1.32',
                'gcc-native/14.2',
            ]
        },
        {
            'name': 'PrgEnv-gnu',
            'target_systems': ['joey'],
            'modules': [
                'PrgEnv-gnu/8.7.0',
                'cray-mpich/9.1.0',
                'gcc-native/14.2',
            ]
        },
    ],
    'logging': [
        {
            'level': 'debug',
            'handlers': [
                {
                    'type': 'file',
                    'name': 'reframe.log',
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_name)s: %(message)s',  # noqa: E501
                    'append': False
                },
                {
                    'type': 'stream',
                    'name': 'stdout',
                    'level': 'info',
                    'format': '%(message)s'
                },
                {
                    'type': 'file',
                    'name': 'reframe.out',
                    'level': 'info',
                    'format': '%(message)s',
                    'append': False
                }
            ],
            'perflog_compat': True,
            'handlers_perflog': [
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'info',
                    'format': '%(asctime)s|reframe %(version)s|%(check_info)s|jobid=%(check_jobid)s|%(check_perf_var)s=%(check_perf_value)s|ref=%(check_perf_ref)s (l=%(check_perf_lower_thres)s, u=%(check_perf_upper_thres)s)',
                    'append': True,
                }
            ]
        }
    ],
    'modes': [
        {
            'name': 'maintenance',
            'options': [
                '--exec-policy=async',
                '--reservation=maintenance',
                '--save-log-files',
                '--tag=acceptance',
                '--timestamp=%F_%H-%M-%S'
            ]
        },
        {
            'name': 'production',
            'options': [
                '--exec-policy=async',
                '--strict',
                '--output=$APPS/UES/$USER/regression/production',
                '--logdir=$APPS/UES/$USER/regression/production/logs',
                '--stage=$SCRATCH/regression/production/stage',
                '--save-log-files',
                '--tag=production',
                '--timestamp=%F_%H-%M-%S'
            ]
        }
    ],
    'general': [
        {
            'check_search_path': [
                'checks/'
            ],
            'check_search_recursive': True
        }
    ]
}
